### ISSUE TITLE
Đặc tả yêu cầu phần mềm sử dụng sơ đồ Use case

### ISSUE THREAD

**Issue by lehai1312** [theleehari/AppTangQua#10]

**Comment by trucquynh-w** [comment]
`document` [https://github.com/theleehari/AppTangQua/blob/main/Documents/YeuCau/DacTaYeuCau/UseCase.pdf](url)

**Comment by lehai1312** [comment]
https://github.com/theleehari/AppTangQua/blob/main/Documents/YeuCau/DacTaYeuCau/Group03_UseCase.pdf
rename file
