### ISSUE TITLE
Thiết kế Sequence Diagram

### ISSUE THREAD

**Issue by lehai1312** [theleehari/AppTangQua#18]

**Comment by vinhduc5984** [comment]
`document` https://github.com/theleehari/AppTangQua/blob/main/Documents/YeuCau/SequenceDiagram.pdf
Sequence Diagram

**Comment by lehai1312** [comment]
https://github.com/theleehari/AppTangQua/blob/main/Documents/YeuCau/Group03_SequenceDiagram.pdf
rename file
