### ISSUE TITLE
Yêu cầu chức năng

### ISSUE THREAD

**Issue by lehai1312** [theleehari/AppTangQua#5]
Phân tích yêu cầu người sử dụng (goal) và yêu cầu hệ thống

**Comment by vinhduc5984** [comment]
`document`  Yêu cầu chức năng update
https://github.com/theleehari/AppTangQua/blob/main/YeuCauChucNang.pdf

**Comment by lehai1312** [comment]
`problems` Cần thêm các chức năng liên quan đến quản lý sản phẩm của người dùng.

**Comment by lehai1312** [comment]
https://github.com/theleehari/AppTangQua/blob/main/Documents/YeuCau/Group03_YeuCauChucNang.pdf
rename file
