### ISSUE TITLE
Đặc tả yêu cầu phần mềm sử dụng ngôn ngữ có cấu trúc

### ISSUE THREAD

**Issue by lehai1312** [theleehari/AppTangQua#8]

**Comment by vinhduc5984** [comment]
'document' đặc tả yêu cầu sử dụng ngôn ngữ có cấu trúc
https://github.com/theleehari/AppTangQua/blob/main/Documents/YeuCau/DacTaYeuCau/DacTaYeuCau_SuDungNgonNguCauTruc.pdf

**Comment by lehai1312** [comment]
https://github.com/theleehari/AppTangQua/blob/main/Documents/YeuCau/DacTaYeuCau/Group03_DacTaYeuCau_SuDungNgonNguCauTruc.pdf
rename file
