### ISSUE TITLE
Tạo document hướng dẫn sử dụng phần mềm/website/app

### ISSUE THREAD

**Issue by lehai1312** [theleehari/AppTangQua#90]

**Comment by vinhduc5984** [comment]
[documemnt]: https://github.com/theleehari/AppTangQua/blob/VinhDuc/Documents/HuongDanSuDung/HuongDanSu%20DungAppQuaTang.docx

**Comment by vinhduc5984** [comment]
https://github.com/theleehari/AppTangQua/blob/VinhDuc/Documents/HuongDanSuDung/HuongDanSu%20DungAppQuaTang.docx

**Comment by theleehari** [comment]
https://github.com/theleehari/AppTangQua/blob/main/Documents/HuongDanSuDung/HuongDanSu%20DungAppQuaTang.docx
